language: php

php:
    - 'hhvm'
    - '5.5'
    - '5.6'
    - '7.0'
    - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

install:
    - composer install

script: bin/phpunit -c src/phpunit.xml --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
